---
title: 'divent: an R Package for Diversity Measures Based on Entropy'
tags:
- R
- biodiversity
- phylogenetic diversity
- functional diversity
- entropy
- Hill numbers
- estimation
- partitioning
authors:
- name: Eric Marcon
  orcid: "0000-0002-5249-321X"
  affiliation: "1, 2"
- name: Florence Puech
  orcid: "0000-0002-5279-6878"
  affiliation: 2
affiliations:
- name: AgroParisTech, Montpellier, France
  index: 1
- name: AMAP, CIRAD, CNRS, INRAE, IRD, Univ Montpellier, Montpellier, France
  index: 2
- name: Université Paris-Saclay, INRAE, AgroParisTech, Paris-Saclay Applied Economics, F-91120, Palaiseau, France
  index: 3
date: "1 February 2026"
bibliography: ../inst/REFERENCES.bib
output: pdf_document
---

# Summary

*divent* is a package for R dedicated to the measurement of biodiversity.
It provides functions to estimate alpha, beta and gamma diversity of communities, including phylogenetic and functional diversity.

It is a reboot of the [*entropart*](https://ericmarcon.github.io/entropart/) package to make it easier to use and computationally more efficient.

Data may be abundance vectors or matrices (the number of individual per species, possibly per site), lists of individuals, or point patterns to address spatially-explicit diversity.
Random communities can be simulated (function `rcommunity`) and spatialized (`rspcommunity`).
The main functions allow computing:

-   Taxonomic entropy: HCDT entropy (`ent_tsallis`) including Shannon and Simpson's entropies.
-   Phylogenetic (`ent_phylo`) or functional (`ent_similarity`) entropy when dissimilarities between species are taken into account in a dendrogram or a similarity matrix.
-   Effective numbers of species, aka Hill numbers, for all entropies (`div_hill`, `div_phylo`, `div_similarity`).
-   Diversity partitioning (`div_part`), i.e. $\alpha$, $\beta$ and $\gamma$ diversity of a set of communities.
-   Diversity profiles (`profile_hill`, `profile_phylo`, `profile_similarity`), with respect to the order or diversity.
-   Diversity accumulation curves (`accum_hill`) with respect to the sample size or coverage.
-   Spatial accumulation of diversity (`accum_sp_hill`) with respect to the distance from individuals, with maps (`plot_map`).

Many estimators are proposed, with sensible automatic choice, to deal with incomplete sampling.

# Statement of need

Measuring biological diversity [@Magurran2004] has been a theoretical and empirical challenge for decades.
A consensus emerged [@Jost2006] to derive it from the theory of information [@Shannon1948].
Individuals are sampled and their species is recorded.

Entropy is the expected amount of information brought by an individual.
Generalized entropy [@Tsallis1988] allows choosing the balance between rare and abundant species.
Classical indices of biodiversity such as Shannon's and Simpson's indices are just special cases of generalized entropy.
Phylogenetic and functional entropy extend the definition taking into account the dissimilarity between species summarized respectively in a dendrogram [@Marcon2014b] or a distance matrix [@Leinster2012].
Finally, Hill numbers [@Hill1973] are the number of species with equal abundance that would have the same entropy as the data, allowing measuring diversity as a effective number.

Data are generally a sample of a community, requiring estimators of entropy [@Marcon2015a].
Estimators of richness (i.e., the number of species), Shannon's entropy or generalized entropy rely on elaborate computing implemented in *divent* (converting estimated entropy into diversity is straightforward).
When the sampling effort is not sufficient to allow estimating asymptotic diversity, standardized diversity for a chosen sampling level is necessary and diversity accumulation with respect to the sample size can be estimated [@Chao2014].

Spatially-explicit diversity raises an increasing interest [@Marcon2023] to address the diversity of the neighborhood of individuals rather than the diversity of an arbitrary plot.
The spatial accumulation of diversity with respect to the size of the neighborhood is an efficient tool to understand community assembly rules [@Shen2013b; @Wiegand2017].
When individual location is not available, the partitioning of the diversity of a set of communities [@Whittaker1960], called $\gamma$ diversity, into the average diversity of communities ($\alpha$ diversity) and their divergence ($\beta$ diversity) is necessary, whatever the diversity considered, for the same purposes.

The *divent* package allows computing all these features of diversity.

# State of the field

The *entropart* R package [@Marcon2014c] was first published in 2015 and augmented following the literature and the research programs of the authors.
It suffers from its incremental development and some obsolete choices such as the organisation of the data, camel-case names of objects, and the insufficient consistence between the behavior of different functions.
These issues justified a complete refactoring.
Spatially-explicit diversity [@Shimatani2001; @Marcon2023] is completely new in *divent*.

The other major R package with the same purposes is *iNEXT* [@Hsieh2014] and its update *iNEXT.3D* [@Chao2021a].
The most important features are identical.
Additionally, *iNEXT.3D* addresses temporal changes [@Chao2021] in diversity (*divent* does not yet), while *divent* addresses spatially-explicit diversity.
*divent* proposes more atomic functions to calculate various aspects of diversity separately (thus faster, allowing including the results in larger analyses) while *iNEXT.3D* relies on the single, end-user oriented `estimate3D` function for all purposes.

*divent* is built on some explicit theoretical choices that differ from those of *iNEXT.3D*:

-   Diversity is explicitely derived from entropy [@Jost2006], following the information theory.
-   Richness estimation is not limited to Chao's estimators [@Marcon2015a]. The jackknife estimator [@Burnham1979] is often employed to reduce diversity underestimation owing to undersampling. Far more estimators of entropy in general are available.
-   Phylogenies must be ultrametric [@Marcon2014b] and no functional distance cutoff following @Pavoine2015a rather than @Chao2019 for theoretical arguments.

# Software design

*divent* is a written in S3, the standard R language.
It follows the state-of-the-art design of R packages [@Wickham2023], namely function naming with prefixes (e.g., `ent_*` functions compute entropy), extensive documentation thanks to packages *roxygen2* [@Wickham2025] for R objects, *Rdpack* [@Boshnakov2026] for references and *pkgdown* [@Wickham2025a] for online manual.
Continuous integration including unit tests [@Wickham2011] and coverage [@Hester2025] is hosted by GitHub.

Generic functions (e.g., `div_hill`) are used to allow two data formats, addressed by their respective method: numeric vectors containing the number of individual per species (function `div_hill.numeric`) or objects of class `species_distributions` (function `div_hill.species_distribution`), which are dataframe whose rows are communities, columns are species and values are abundances (objects of class `abundances`, that inherits from `species_distributions`) or probabilities (class `probabilities`).
Functions to convert a classical abundance matrix, a list of individuals or a point pattern to an `abundances` object are provided.

# Research impact statement

*divent* is a reboot of the *entropart* package [@Marcon2014c] that is widely used (around 40 citations every year according to Google Scholar).
It came with an open-access textbook [@Marcon2014d] written in French and downloaded more than 50,000 times which is being rewritten in English, based on *divent*.

# AI usage disclosure

No AI tools were used at any stage of the package development nor in this article.

# Acknowledgements

This work benefited from the support of “Investissements d’avenir” of the French National Agency for Research (Labex CEBA, ref. ANR-10-LABX-25-01).
The authors thank [Bruno Hérault](https://agents.cirad.fr/Bruno+HERAULT) for his contributions to the [entropart](https://ericmarcon.github.io/entropart/) package.

# References
